# docker compose -p kaki-go -f docker-compose.yml up -d --force-recreate

services:
  postgres:
    container_name: postgresdb-kaki
    image: postgres:17.0
    restart: always
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh 
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      APP_ENV: ${APP_ENV}
    ports:
      - "${POSTGRES_PORT}:5432"
    command: [ "bash", "-c", "docker-entrypoint.sh postgres & sleep 5 && bash /docker-entrypoint-initdb.d/init-db.sh && wait" ]

  pgadmin:
    container_name: pgadmin4-kaki
    image: dpage/pgadmin4:9
    restart: always
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      MAX_LOGIN_ATTEMPTS: ${MAX_LOGIN_ATTEMPTS}
    ports:
      - "${PGADMIN_PORT}:80"

volumes:
  postgres-data:
  pgadmin-data:
