# 
# # RUN line below for dev & test # #
# docker-compose -p kaki-go --profile dev -f docker-compose.yml up -d --force-recreate
# # RUN line below for prod # #
# docker-compose -p kaki-go --profile prod -f docker-compose.yml up -d --force-recreate
#

services:
  postgres:
    container_name: postgresdb-kaki
    image: postgres:17.0
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: >
      bash -c "
        echo '✅   Starting PostgreSQL...';
        docker-entrypoint.sh postgres & 

        # Wait for PostgreSQL to be fully ready
        echo '⏳   Waiting for PostgreSQL to start...';
        until pg_isready -h localhost -p 5432 -U $POSTGRES_USER; do
          echo '⏳   Still waiting for PostgreSQL...';
          sleep 5;
        done;

        echo '✅   PostgreSQL is ready! Proceeding with initialization...';

        # Ensure the main database exists
        echo \"Checking if main database '$POSTGRES_DB' exists...\";
        if psql -U \"$POSTGRES_USER\" -d postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$POSTGRES_DB'\" | grep -q 1; then
          echo '✅   Main database \"$POSTGRES_DB\" already exists.';
        else
          echo '🚀   Creating main database: \"$POSTGRES_DB\"';
          psql -U \"$POSTGRES_USER\" -d postgres -c \"CREATE DATABASE \\\"$POSTGRES_DB\\\";\";
        fi;

        # Check if test database exists and create schema 'public'
        echo \"Checking if test database '$POSTGRES_DB_TEST' exists...\";
        if psql -U \"$POSTGRES_USER\" -d postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$POSTGRES_DB_TEST'\" | grep -q 1; then
          echo '✅   Test database \"$POSTGRES_DB_TEST\" already exists.';
        else
          echo '🚀   Creating test database: \"$POSTGRES_DB_TEST\"';
          psql -U \"$POSTGRES_USER\" -d postgres -c \"CREATE DATABASE \\\"$POSTGRES_DB_TEST\\\";\";
        fi;

        echo \"Checking if dev database '$POSTGRES_DB_DEV' exists...\";
        if psql -U \"$POSTGRES_USER\" -d postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$POSTGRES_DB_DEV'\" | grep -q 1; then
          echo '✅   Dev database \"$POSTGRES_DB_DEV\" already exists.';
        else
          echo '🚀   Creating dev database: \"$POSTGRES_DB_DEV\"';
          psql -U \"$POSTGRES_USER\" -d postgres -c \"CREATE DATABASE \\\"$POSTGRES_DB_DEV\\\";\";
        fi;

        echo '🔧   Ensuring schema public exists on main database...'
        psql -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -c 'CREATE SCHEMA IF NOT EXISTS public;';
        
        echo '🔧   Ensuring schema public exists on test database...';
        psql -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB_TEST\" -c 'CREATE SCHEMA IF NOT EXISTS public;';

        echo '🔧   Ensuring schema public exists on dev database...'
        psql -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB_DEV\" -c 'CREATE SCHEMA IF NOT EXISTS public;';

        echo '🎉   Database initialization complete!';

        # Keep PostgreSQL running in the foreground to prevent container exit
        wait
      "
    networks:
      - kaki-network

  pgadmin:
    container_name: pgadmin4-kaki
    image: dpage/pgadmin4:9
    restart: always
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      MAX_LOGIN_ATTEMPTS: ${MAX_LOGIN_ATTEMPTS}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - kaki-network

  fiber-app:
    container_name: fiber-api-kaki
    build: .
    restart: always
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    networks:
      - kaki-network
    profiles:
      - prod  # Runs only in production

  prometheus:
    container_name: prometheus-kaki
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - kaki-network

  grafana:
    image: grafana/grafana
    container_name: grafana-kaki
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "${GRAFANA_ALIAS_PORT}:${GRAFANA_PORT}"
    depends_on:
      - prometheus
    networks:
      - kaki-network
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  loki:
    user: root
    restart: always
    container_name: loki-kaki
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-index:/loki/index
      - loki-cache:/loki/cache
      - loki-chunks:/loki/chunks
      - loki-compactor:/loki/compactor
      - loki-wal:/loki/wal
    networks:
      - kaki-network

  minio:
    container_name: minio-kaki
    image: quay.io/minio/minio
    restart: always
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - kaki-network
    profiles:
      - dev
      - test

      
networks:
  kaki-network:

volumes:
  postgres-data:
  pgadmin-data:
  grafana-data:
  loki-index:
  loki-cache:
  loki-chunks:
  loki-compactor:
  loki-wal:
  minio-data:
