// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "fiber@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/company": {
            "post": {
                "description": "Create a company",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Create company",
                "parameters": [
                    {
                        "description": "Company",
                        "name": "company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DTO.CreateCompany"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/company/name/{name}": {
            "get": {
                "description": "Retrieve a company by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get company by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/company/tax_id/{tax_id}": {
            "get": {
                "description": "Retrieve a company by its tax identification number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get company by tax ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company Tax ID",
                        "name": "tax_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/company/{id}": {
            "get": {
                "description": "Retrieve a company by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Get company by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a company by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Delete company by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a company by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Company"
                ],
                "summary": "Update company by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Company",
                        "name": "company",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DTO.Company"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{resource}": {
            "get": {
                "description": "Retrieve all records of a given resource",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Get all records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new entity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Create a new record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entity Data",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{resource}/force": {
            "get": {
                "description": "Retrieve all records including soft-deleted ones",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Get all records (force)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{resource}/{id}": {
            "get": {
                "description": "Retrieve a single record by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Get a record by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft delete an entity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Delete a record by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing record",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Update a record by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Entity Data",
                        "name": "entity",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{resource}/{id}/force": {
            "get": {
                "description": "Retrieve a single record by its ID including soft-deleted ones",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Get all records (force)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {}
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently delete an entity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AutoGenerated"
                ],
                "summary": "Force delete a record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/DTO.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "DTO.Branch": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "company_id": {
                    "type": "integer"
                },
                "complement": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.UserPopulated"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.ServicePopulated"
                    }
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "zip_code": {
                    "type": "string"
                }
            }
        },
        "DTO.Company": {
            "description": "Company Full DTO",
            "type": "object",
            "properties": {
                "branches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.Branch"
                    }
                },
                "company_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.CompanyType"
                    }
                },
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.UserPopulated"
                    }
                },
                "id": {
                    "description": "Primary key",
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "Your Company Name"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.ServicePopulated"
                    }
                },
                "tax_id": {
                    "type": "string",
                    "example": "00000000000000"
                }
            }
        },
        "DTO.CompanyType": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Your Company Type Name"
                }
            }
        },
        "DTO.CreateCompany": {
            "type": "object",
            "properties": {
                "company_types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DTO.CompanyType"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Your Company Name"
                },
                "tax_id": {
                    "type": "string",
                    "example": "00000000000000"
                }
            }
        },
        "DTO.ErrorResponse": {
            "description": "Error Response Model",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Not Found"
                }
            }
        },
        "DTO.ServicePopulated": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                }
            }
        },
        "DTO.UserPopulated": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fiber Example API",
	Description:      "Swagger API for testing and debugging",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
